language: python
python:
    - "2.7"

install:
    - sudo pip install unittest2
    - sudo apt-get install wget
    - sudo python setup.py install

before_script:
    - mkdir /var/tmp/tests
    - wget www.google.es > /var/tmp/tests/sample_data.json

script:
    - nosetests -v
    - travis-ci-tutorial -f test.json
